# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mikail Freitas
tagline:          'Developer guy'
description:      "Software developer"
url:              http://mikail.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

gems:
  [jekyll-paginate, jekyll-gist]

# Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
