# Site wide configuration

title: Mikail Freitas
description: "It's me alright"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: http://mikailcf.github.io
url: http://mikail.io
url: http://localhost:4000

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Mikail Freitas
  web: http://mikail.io
  email: contact@mikail.io
  twitter: 
  bio: "Cool dev guy."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]